### ISSUE TITLE
AttributeError: module 'nglpy' has no attribute 'Graph'

### ISSUE THREAD

**Issue by yiyusheng** [maljovec/pyerg#16]
When I run your example, it outputs the Error: AttributeError: module 'nglpy' has no attribute 'Graph'
I checked dir(nglpy) and dir(nglpy.ngl) but do not find Graph function. 
I find nglpy.ngl.nglGraph and thought it may be the right function , it also throw a error out 
'TypeError: __init__() missing 3 required positional arguments: 'maxN', 'beta', and 'edgeIndices''
Please repair the example, thank you!

**Comment by dmaljovec** [comment]
Oops, I recently released a new version with a new API, and I think I forgot to change the example, thanks for pointing this out. I will update the example in the README.

**Comment by dmaljovec** [comment]
I think this should be fixed with https://github.com/maljovec/nglpy/commit/71479f142e79c3ce8b62e22daf27b18a9785e432. Please feel free to reopen if this does not fix your issue. Thank you for pointing this out!
